services:
  ideal-link-extractor:
    build: .
    container_name: ideal-link-extractor
    ports:
      - "8060:8060"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - IDEAL_PRE_PROXY=
      - KAKAO_PRE_PROXY=
      - UPI_PRE_PROXY=
    volumes:
      - ./nl_proxy_seeds.txt:/app/nl_proxy_seeds.txt
      - ./vn_proxy_seeds.txt:/app/vn_proxy_seeds.txt
      - ./token.txt:/app/token.txt
      - ./turkey_card/tr_proxy_seeds.txt:/app/turkey_card/tr_proxy_seeds.txt
      - ./turkey_card/us_proxy_seeds.txt:/app/turkey_card/us_proxy_seeds.txt
      - ./turkey_card/token.txt:/app/turkey_card/token.txt
      - ./pix/br_proxy_seeds.txt:/app/pix/br_proxy_seeds.txt
      - ./pix/vn_proxy_seeds.txt:/app/pix/vn_proxy_seeds.txt
      - ./twint/ch_proxy_seeds.txt:/app/twint/ch_proxy_seeds.txt
      - ./twint/vn_proxy_seeds.txt:/app/twint/vn_proxy_seeds.txt
      - ./upi/in_proxy_seeds.txt:/app/upi/in_proxy_seeds.txt
      - ./upi/vn_proxy_seeds.txt:/app/upi/vn_proxy_seeds.txt
      - ./kakao/kr_proxy_seeds.txt:/app/kakao/kr_proxy_seeds.txt
      - ./kakao/vn_proxy_seeds.txt:/app/kakao/vn_proxy_seeds.txt
      - ./kakao/token.txt:/app/kakao/token.txt
      - ./upi/proxy_seeds.txt:/app/upi/proxy_seeds.txt
      - ./upi/token.txt:/app/upi/token.txt
      - ./blik/proxy_seeds.txt:/app/blik/proxy_seeds.txt
      - ./blik/token.txt:/app/blik/token.txt
      - ./pix/token.txt:/app/pix/token.txt
      - ./twint/token.txt:/app/twint/token.txt
      - ./logs:/app/logs
